/**
 * RustRide Companion App - Type Definitions
 *
 * Common type definitions used throughout the app.
 */

// Connection status types
export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'authenticated';

// Session types
export type SessionType = 'free_ride' | 'workout';
export type SessionState = 'idle' | 'active' | 'paused' | 'completed';

// Metrics types
export interface LiveMetrics {
  power_watts: number;
  heart_rate_bpm: number | null;
  cadence_rpm: number | null;
  speed_kph: number;
  distance_km: number;
  calories: number;
}

// Session status info from server
export interface SessionStatusInfo {
  session_id: string;
  session_type: SessionType;
  workout_name?: string;
  workout_path?: string;
  is_paused: boolean;
  elapsed_secs: number;
  current_interval_index?: number;
  total_intervals?: number;
  current_interval_name?: string;
  target_power_watts?: number;
  interval_remaining_secs?: number;
}

// Ride summary for history list
export interface RideSummary {
  id: string;
  date: string;
  duration_secs: number;
  distance_km: number;
  avg_power_watts: number;
  workout_name?: string;
  is_workout?: boolean;
}

/**
 * Power zone time distribution (seconds spent in each zone)
 */
export interface PowerZoneDistribution {
  z1_recovery: number;
  z2_endurance: number;
  z3_tempo: number;
  z4_threshold: number;
  z5_vo2max: number;
  z6_anaerobic: number;
  z7_neuromuscular: number;
}

/**
 * Heart rate zone time distribution (seconds spent in each zone)
 */
export interface HrZoneDistribution {
  z1: number;
  z2: number;
  z3: number;
  z4: number;
  z5: number;
}

// Detailed ride information
export interface RideDetailInfo {
  ride_id: string;
  started_at: string;
  ended_at: string;
  duration_secs: number;
  distance_km: number;
  calories: number;
  avg_power_watts: number | null;
  max_power_watts: number | null;
  normalized_power_watts: number | null;
  avg_heart_rate_bpm: number | null;
  max_heart_rate_bpm: number | null;
  avg_cadence_rpm: number | null;
  tss: number | null;
  intensity_factor: number | null;
  is_workout: boolean;
  workout_name: string | null;
  // Zone distributions (optional - may not be available for all rides)
  power_zone_distribution?: PowerZoneDistribution | null;
  hr_zone_distribution?: HrZoneDistribution | null;
}

// Server discovery result
export interface DiscoveredServer {
  name: string;
  host: string;
  port: number;
  version?: string;
}

/**
 * QR code connection data format.
 * Matches the JSON format generated by CompanionQrCode in src/companion/qr.rs
 *
 * Example:
 * {
 *   "url": "ws://192.168.1.100:9876",
 *   "pin": "123456",
 *   "version": "1"
 * }
 */
export interface QrConnectionData {
  /** WebSocket URL (e.g., "ws://192.168.1.100:9876") */
  url: string;
  /** Optional PIN for authentication (6 digits) */
  pin?: string;
  /** Protocol version for compatibility checking */
  version: string;
}

/**
 * Parse QR code data into connection data.
 * Returns null if parsing fails.
 */
export function parseQrConnectionData(data: string): QrConnectionData | null {
  try {
    const parsed = JSON.parse(data);

    // Validate required fields
    if (typeof parsed.url !== 'string' || !parsed.url) {
      return null;
    }
    if (typeof parsed.version !== 'string' || !parsed.version) {
      return null;
    }

    // Validate URL format (must be ws:// or wss://)
    if (!parsed.url.startsWith('ws://') && !parsed.url.startsWith('wss://')) {
      return null;
    }

    // Validate PIN if present (should be 6 digits)
    if (parsed.pin !== undefined && parsed.pin !== null) {
      if (typeof parsed.pin !== 'string' || !/^\d{6}$/.test(parsed.pin)) {
        return null;
      }
    }

    return {
      url: parsed.url,
      pin: parsed.pin || undefined,
      version: parsed.version,
    };
  } catch {
    return null;
  }
}

/**
 * Extract host and port from a WebSocket URL.
 * Returns null if parsing fails.
 */
export function parseWebSocketUrl(wsUrl: string): { host: string; port: number } | null {
  try {
    // Parse using regex since React Native's URL implementation may be incomplete
    const match = wsUrl.match(/^wss?:\/\/([^:/]+)(?::(\d+))?/);
    if (!match) {
      return null;
    }

    const host = match[1];
    const port = match[2] ? parseInt(match[2], 10) : 9876; // Default port

    if (!host || isNaN(port)) {
      return null;
    }

    return { host, port };
  } catch {
    return null;
  }
}

// App settings
export interface AppSettings {
  units: 'metric' | 'imperial';
  keepScreenAwake: boolean;
  hapticFeedback: 'off' | 'light' | 'medium' | 'strong';
  theme: 'system' | 'light' | 'dark';
}

// ============================================================
// WebSocket Protocol Types
// ============================================================

/**
 * Request messages sent to the RustRide desktop app.
 * Matches CompanionRequest from src/companion/types.rs
 */
export type CompanionRequest =
  | { type: 'auth'; pin: string }
  | { type: 'get_session_status' }
  | { type: 'subscribe_metrics' }
  | { type: 'unsubscribe_metrics' }
  | { type: 'workout_pause' }
  | { type: 'workout_resume' }
  | { type: 'workout_skip' }
  | { type: 'workout_stop' }
  | { type: 'adjust_resistance'; delta: number }
  | { type: 'get_ride_history'; limit: number; offset: number }
  | { type: 'get_ride_details'; ride_id: string }
  | { type: 'ping' };

/**
 * Error codes returned by the server.
 * Matches CompanionErrorCode from src/companion/types.rs
 */
export type CompanionErrorCode =
  | 'AUTH_REQUIRED'
  | 'INVALID_PIN'
  | 'NO_SESSION'
  | 'SESSION_ACTIVE'
  | 'UNKNOWN_COMMAND'
  | 'INVALID_PARAMS'
  | 'RATE_LIMITED'
  | 'INTERNAL_ERROR';

/**
 * Response messages received from the RustRide desktop app.
 * Matches CompanionResponse from src/companion/types.rs
 */
export type CompanionResponse =
  | { type: 'auth_ok'; session_id: string }
  | { type: 'auth_failed'; reason: string }
  | { type: 'session_status'; active: boolean; session: SessionStatusInfo | null }
  | { type: 'subscribed_metrics' }
  | { type: 'unsubscribed_metrics' }
  | { type: 'command_ok'; command: string }
  | { type: 'command_failed'; command: string; error: string }
  | { type: 'ride_history'; rides: RideSummary[]; total: number }
  | { type: 'ride_details'; ride: RideDetailInfo }
  | { type: 'pong' }
  | { type: 'error'; code: CompanionErrorCode; message: string };

/**
 * Event messages pushed from the RustRide desktop app.
 * Matches CompanionEvent from src/companion/types.rs
 */
export type CompanionEvent =
  | {
      type: 'metrics';
      power_watts: number | null;
      heart_rate_bpm: number | null;
      cadence_rpm: number | null;
      speed_kmh: number | null;
      distance_km: number;
      elapsed_secs: number;
      calories: number;
    }
  | {
      type: 'session_state_changed';
      state: 'idle' | 'starting' | 'active' | 'paused' | 'stopping' | 'completed';
      session: SessionStatusInfo | null;
    }
  | {
      type: 'interval_changed';
      interval_index: number;
      total_intervals: number;
      interval_name: string;
      target_power_watts: number;
      duration_secs: number;
    }
  | {
      type: 'disconnecting';
      reason: string;
    };

/**
 * Union type for all possible WebSocket messages from the server
 */
export type ServerMessage = CompanionResponse | CompanionEvent;

/**
 * Helper to check if a message is an event (vs response)
 */
export function isCompanionEvent(message: ServerMessage): message is CompanionEvent {
  return (
    message.type === 'metrics' ||
    message.type === 'session_state_changed' ||
    message.type === 'interval_changed' ||
    message.type === 'disconnecting'
  );
}

/**
 * Helper to check if a message is a response
 */
export function isCompanionResponse(message: ServerMessage): message is CompanionResponse {
  return !isCompanionEvent(message);
}
